### PR TITLE
agent: pub/sub concurrency for svcs

### PR DESCRIPTION
**Pull request by sknat**
Add a simple pub/sub channel registration &
publishing mechanism for goroutines running
services in the calico-vpp-agent.

This aims at allowing a simpler concurrency
model between services, to :
- avoid potential deadlocks
- make implementing restarts / conf updates easier
- reduce the api call / behavior diversity (e.g. when
getting the nodeIp)

Signed-off-by: Nathan Skrzypczak <nathan.skrzypczak@gmail.com>

### CODE REVIEW

**Comment by sknat** [comment]
@jjgraham this should be rebased on your PR #186 , tell me if I missed anything or broke expected behavior.
On the changes that might be impacting you :
- `routing/connectivity/*` moved to `connectivity/*` in its own component.
- There is now a single `common.go` in `common/` in which `routing/common/common.go` was merged
- The `ConnectivityEvent` is now called `CalicoVppEvent` and leveraged by all goroutines
- (this also changes calls to generate events - `common.SendEvent` - and operations on the BGPServer)

**Review by AloysAugustin — APPROVED** [review]

**Comment by AloysAugustin** [comment]
I think you meant @zvfvrv ^

**Comment by zvfvrv** [comment]
Hi @sknat, just tested and there is just a line of code missing :) 
inside calico-vpp-agent/cmd/calico_vpp_dataplane.go around L182 this line is missing: localSIDWatcher.SetOurBGPSpec(ourBGPSpec)  
Thanks!

**Comment by sknat** [comment]
Thanks @zvfvrv 😄 Sorry this did slip through.
Should be fixed now.

**Pull request merged**
